export const RECEIVE_PAGES = 'RECEIVE_PAGES'

export const RECEIVE_SITE = 'RECEIVE_SITE'
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS'
export const RECEIVE_CHAPTER = 'RECEIVE_CHAPTER'
export const RECEIVE_THEME = 'RECEIVE_THEME'

export const UPDATE_APP = 'UPDATE_APP'
